#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=D:\Software\flutter_windows_1.20.0-stable\flutter"
export "FLUTTER_APPLICATION_PATH=D:\Project\digi_pm_skin"
export "FLUTTER_TARGET=lib\main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build\ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=D:\Software\flutter_windows_1.20.0-stable\flutter\bin\cache\artifacts\engine\ios"
export "FLUTTER_BUILD_NAME=1.5.6"
export "FLUTTER_BUILD_NUMBER=14"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
